apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: admin-network
  annotations:
    github.com/project-slug: mattjmorrison-homelab/admin-network
spec:
  type: iac
  owner: mattjmorrison-homelab
  lifecycle: experimental
  system: dns-networking
